#!/bin/bash

version=1.79.1

  xmlcatalog --noout --del "/usr/share/xml/docbook/xsl-stylesheets-$version" /etc/xml/catalog

  xmlcatalog --noout --del "/usr/share/xml/docbook" /etc/xml/catalog
  xmlcatalog --noout --del "file:///etc/xml/docbook" /etc/xml/catalog
