#!/bin/bash

if [ ! $(getent group netdev) ]; then
	echo "creating netdev group..."
	echo "* please add your user into netdev group"
	groupadd -fg 86 netdev
fi

if [ $(grep ONBOOT /etc/sysconfig/ifconfig.wifi0) = 'ONBOOT="yes"' ]; then
	echo "Disable ONBOOT for wpa_supplicant..."
	sed -i 's/ONBOOT="yes"/ONBOOT="no"/' /etc/sysconfig/ifconfig.wifi0
fi
