#!/bin/bash -e

. build-properties
. pkgversion

PROGRAM="linux-${LINUX_VER}"
TARBALL="$PROGRAM.tar.*"

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	make mrproper
	make INSTALL_HDR_PATH=dest headers_install
	cp -rv dest/include/* /tools/include
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
