#!/bin/bash -e

. build-properties
. pkgversion

PROGRAM="ncurses-${NCURSES_VER}"
TARBALL="$PROGRAM.tar.*"

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	sed -i s/mawk// configure
	
	./configure --prefix=/tools \
				--with-shared   \
				--without-debug \
				--without-ada   \
				--enable-widec  \
				--enable-overwrite
	make
	make install
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
