#!/bin/bash -e

. $(dirname $0)/build-properties
. $(dirname $0)/pkgversion

PROGRAM="util-linux-${UTILLINUX_VER}"
TARBALL="$PROGRAM.tar.*"

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	./configure --prefix=/tools                \
				--without-python               \
				--disable-makeinstall-chown    \
				--without-systemdsystemunitdir \
				--without-ncurses              \
				PKG_CONFIG=""
	make
	make install
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
