#!/bin/bash -e

$(dirname $0)/01-binutils-pass1
$(dirname $0)/02-gcc-pass1
$(dirname $0)/03-linux-api-headers
$(dirname $0)/04-glibc
$(dirname $0)/05-libstdc++
$(dirname $0)/06-binutils-pass2
$(dirname $0)/07-gcc-pass2
$(dirname $0)/08-tcl-core
$(dirname $0)/09-expect
$(dirname $0)/10-dejagnu
$(dirname $0)/11-ncurses
$(dirname $0)/12-bash
$(dirname $0)/13-bison
$(dirname $0)/14-bzip2
$(dirname $0)/15-coreutils
$(dirname $0)/16-diffutils
$(dirname $0)/17-file
$(dirname $0)/18-findutils
$(dirname $0)/19-gawk
$(dirname $0)/20-gettext
$(dirname $0)/21-grep
$(dirname $0)/22-gzip
$(dirname $0)/23-m4
$(dirname $0)/24-make
$(dirname $0)/25-patch
$(dirname $0)/26-perl
$(dirname $0)/27-sed
$(dirname $0)/28-tar
$(dirname $0)/29-texinfo
$(dirname $0)/30-util-linux
$(dirname $0)/31-xz
$(dirname $0)/cleaning

echo "*******************************************************"
echo "Toolchain build complete"
echo "Dont forget to run 'sudo chown -Rv 0:0 /mnt/lfs'"
echo "to change toolchain permission to root"
echo "*******************************************************"
