#!/bin/bash -e

NYX=/mnt/lfs

ln -sfv $NYX/tools /

mkdir -pv $NYX/{dev,proc,sys,run}

mknod -m 600 $NYX/dev/console c 5 1 || true
mknod -m 666 $NYX/dev/null c 1 3 || true

mkdir -pv $NYX/{bin,boot,etc/opt,home,lib/firmware,mnt,opt}
mkdir -pv $NYX/{media/{floppy,cdrom},sbin,srv,var}
install -dv -m 0750 $NYX/root
install -dv -m 1777 $NYX/tmp $NYX/var/tmp
mkdir -pv $NYX/usr/{,local/}{bin,include,lib,sbin,src}
mkdir -pv $NYX/usr/{,local/}share/{color,dict,doc,info,locale,man}
mkdir -pv  $NYX/usr/{,local/}share/{misc,terminfo,zoneinfo}
mkdir -pv  $NYX/usr/libexec
mkdir -pv $NYX/usr/{,local/}share/man/man{1..8}
mkdir -pv $NYX/lib64

mkdir -pv $NYX/var/{log,mail,spool}
ln -svf /run $NYX/var/run
ln -svf /run/lock $NYX/var/lock
mkdir -pv $NYX/var/{opt,cache,lib/{color,misc,locate},local}

ln -svf /tools/bin/{bash,cat,dd,echo,ln,pwd,rm,stty} $NYX/bin
ln -svf /tools/bin/{install,perl} $NYX/usr/bin
ln -svf /tools/lib/libgcc_s.so{,.1} $NYX/usr/lib
ln -svf /tools/lib/libstdc++.{a,so{,.6}} $NYX/usr/lib
ln -svf bash $NYX/bin/sh

ln -svf /proc/self/mounts $NYX/etc/mtab
echo "nameserver 8.8.8.8" > $NYX/etc/resolv.conf

cat > $NYX/etc/passwd << "EOF"
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/bin/false
daemon:x:6:6:Daemon User:/dev/null:/bin/false
messagebus:x:18:18:D-Bus Message Daemon User:/var/run/dbus:/bin/false
nobody:x:99:99:Unprivileged User:/dev/null:/bin/false
EOF

cat > $NYX/etc/group << "EOF"
root:x:0:
bin:x:1:daemon
sys:x:2:
kmem:x:3:
tape:x:4:
tty:x:5:
daemon:x:6:
floppy:x:7:
disk:x:8:
lp:x:9:
dialout:x:10:
audio:x:11:
video:x:12:
utmp:x:13:
usb:x:14:
cdrom:x:15:
adm:x:16:
messagebus:x:18:
systemd-journal:x:23:
input:x:24:
mail:x:34:
nogroup:x:99:
users:x:999:
EOF

touch $NYX/var/log/{btmp,lastlog,faillog,wtmp}
chgrp -v utmp $NYX/var/log/lastlog
chmod -v 664  $NYX/var/log/lastlog
chmod -v 600  $NYX/var/log/btmp
