#!/bin/bash -e

. build-properties

PROGRAM="tcl-core8.6.7-src"
TARBALL="$PROGRAM.tar.gz"

cd $SOURCE_DIR

if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	cd unix
	./configure --prefix=/tools
	make
	make install
	
	chmod -v u+w /tools/lib/libtcl8.6.so
	make install-private-headers
	ln -sv tclsh8.6 /tools/bin/tclsh
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
