#!/bin/bash -e

. build-properties

PROGRAM="bash-4.4.12"
TARBALL="$PROGRAM.tar.gz"

cd $SOURCE_DIR

if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	./configure --prefix=/tools --without-bash-malloc
	make
	make install
	ln -sv bash /tools/bin/sh
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
