#!/bin/bash -e

. build-properties

PROGRAM="gzip-1.8"
TARBALL="$PROGRAM.tar.xz"

cd $SOURCE_DIR

if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	./configure --prefix=/tools
	make
	make install
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
