#!/bin/bash -e

. build-properties

PROGRAM="util-linux-2.31"
TARBALL="$PROGRAM.tar.xz"

cd $SOURCE_DIR

if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	./configure --prefix=/tools                \
				--without-python               \
				--disable-makeinstall-chown    \
				--without-systemdsystemunitdir \
				--without-ncurses              \
				PKG_CONFIG=""
	make
	make install
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
