#!/bin/bash -e

. $(dirname $0)/build-properties
. $(dirname $0)/pkgversion

PROGRAM="mpfr-${MPFR_VER}"
TARBALL="$PROGRAM.tar.xz"

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	patch -Np1 -i ${SOURCE_DIR}/mpfr-3.1.5-fixes-1.patch
	
	LDFLAGS="-Wl,-rpath,/cross-tools/lib" \
	./configure \
		--prefix=/cross-tools \
		--disable-static \
		--with-gmp=/cross-tools
	make
	make install
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

[ $PIPESTATUS = 0 ] && echo "$PROGRAM" > /tools/$0 || exit $PIPESTATUS

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
