#!/bin/bash -e

. $(dirname $0)/build-properties
. $(dirname $0)/pkgversion

PROGRAM="gcc-${GCC_VER}"
TARBALL="$PROGRAM.tar.bz2"

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	patch -Np1 -i ${SOURCE_DIR}/gcc-${GCC_VER}-specs-1.patch
	
	echo -en '\n#undef STANDARD_STARTFILE_PREFIX_1\n#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"\n' >> gcc/config/linux.h
	echo -en '\n#undef STANDARD_STARTFILE_PREFIX_2\n#define STANDARD_STARTFILE_PREFIX_2 ""\n' >> gcc/config/linux.h

	touch /tools/include/limits.h
	
	mkdir -v build
	cd build

	AR=ar \
	LDFLAGS="-Wl,-rpath,/cross-tools/lib" \
	../configure \
		--prefix=/cross-tools \
		--build=${CLFS_HOST} \
		--host=${CLFS_HOST} \
		--target=${CLFS_TARGET} \
		--with-sysroot=${CLFS} \
		--with-local-prefix=/tools \
		--with-native-system-header-dir=/tools/include \
		--disable-shared \
		--with-mpfr=/cross-tools \
		--with-gmp=/cross-tools \
		--with-mpc=/cross-tools \
		--without-headers \
		--with-newlib \
		--disable-decimal-float \
		--disable-libgomp \
		--disable-libssp \
		--disable-libatomic \
		--disable-libitm \
		--disable-libsanitizer \
		--disable-libquadmath \
		--disable-libvtv \
		--disable-libcilkrts \
		--disable-libstdc++-v3 \
		--disable-threads \
		--with-isl=/cross-tools \
		--enable-languages=c \
		--with-glibc-version=2.25
	make all-gcc all-target-libgcc
	make install-gcc install-target-libgcc
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

[ $PIPESTATUS = 0 ] && echo "$PROGRAM" > /tools/$0 || exit $PIPESTATUS

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
