#!/bin/bash -e

[ -f /tools/$0 ] && exit 0

. $(dirname $0)/build-properties
. $(dirname $0)/build-properties-extra
. $(dirname $0)/pkgversion

PROGRAM="binutils-${BINUTILS_VER}"
TARBALL="$PROGRAM.tar.bz2"

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	mkdir -v build
	cd build

	../configure \
		--prefix=/tools \
		--libdir=/tools/lib64 \
		--with-lib-path=/tools/lib64:/tools/lib \
		--build=${CLFS_HOST} \
		--host=${CLFS_TARGET} \
		--target=${CLFS_TARGET} \
		--disable-nls \
		--enable-shared \
		--enable-64-bit-bfd \
		--enable-gold=yes \
		--enable-plugins \
		--with-system-zlib \
		--enable-threads
	make
	make install
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

[ $PIPESTATUS = 0 ] && echo "$PROGRAM" > /tools/$0 || exit $PIPESTATUS

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
