#!/bin/bash -e

. $(dirname $0)/build-properties
. $(dirname $0)/build-properties-extra
. $(dirname $0)/pkgversion

PROGRAM="gcc-${GCC_VER}"
TARBALL="$PROGRAM.tar.bz2"

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	patch -Np1 -i ${SOURCE_DIR}/gcc-${GCC_VER}-specs-1.patch
	
	echo -en '\n#undef STANDARD_STARTFILE_PREFIX_1\n#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"\n' >> gcc/config/linux.h
	echo -en '\n#undef STANDARD_STARTFILE_PREFIX_2\n#define STANDARD_STARTFILE_PREFIX_2 ""\n' >> gcc/config/linux.h
	
	cp -v gcc/Makefile.in{,.orig}
	sed 's@\./fixinc\.sh@-c true@' gcc/Makefile.in.orig > gcc/Makefile.in

	mkdir -v build
	cd build

	../configure \
		--prefix=/tools \
		--libdir=/tools/lib64 \
		--build=${CLFS_HOST} \
		--host=${CLFS_TARGET} \
		--target=${CLFS_TARGET} \
		--with-local-prefix=/tools \
		--enable-languages=c,c++ \
		--with-system-zlib \
		--with-native-system-header-dir=/tools/include \
		--disable-libssp \
		--enable-install-libiberty
	make AS_FOR_TARGET="${AS}" \
		LD_FOR_TARGET="${LD}"
	make -j1 install
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

[ $PIPESTATUS = 0 ] && echo "$PROGRAM" > /tools/$0 || exit $PIPESTATUS

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
