#!/bin/bash -e

[ -f /tools/$0 ] && exit 0

. $(dirname $0)/build-properties
. $(dirname $0)/build-properties-extra
. $(dirname $0)/pkgversion

PROGRAM="util-linux-${UTILLINUX_VER}"
TARBALL="$PROGRAM.tar.xz"

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	NCURSESW6_CONFIG=" " \
	NCURSES6_CONFIG=" " \
	NCURSESW5_CONFIG=" " \
	NCURSES5_CONFIG=" " \
		./configure \
		--prefix=/tools \
		--build=${CLFS_HOST} \
		--host=${CLFS_TARGET} \
		--libdir='${prefix}'/lib64 \
		--disable-makeinstall-chown \
		--disable-makeinstall-setuid \
		--disable-nologin \
		--without-python
	make
	make install
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

[ $PIPESTATUS = 0 ] && echo "$PROGRAM" > /tools/$0 || exit $PIPESTATUS

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
