#!/bin/bash -e

[ -f /tools/$0 ] && exit 0

. $(dirname $0)/build-properties
. $(dirname $0)/build-properties-extra
. $(dirname $0)/pkgversion

PROGRAM="vim-${VIM_VER}"
TARBALL="$PROGRAM.tar.bz2"

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	patch -Np1 -i ${SOURCE_DIR}/vim-8.0-branch_update-1.patch
	
	cat > src/auto/config.cache << "EOF"
vim_cv_getcwd_broken=no
vim_cv_memmove_handles_overlap=yes
vim_cv_stat_ignores_slash=no
vim_cv_terminfo=yes
vim_cv_toupper_broken=no
vim_cv_tty_group=world
vim_cv_tgent=zero
EOF

	echo '#define SYS_VIMRC_FILE "/tools/etc/vimrc"' >> src/feature.h

	./configure \
		--build=${CLFS_HOST} \
		--host=${CLFS_TARGET} \
		--prefix=/tools \
		--enable-gui=no \
		--disable-gtktest \
		--disable-xim \
		--disable-gpm \
		--without-x \
		--disable-netbeans \
		--with-tlib=ncurses
	make
	make -j1 install
	ln -sv vim /tools/bin/vi

	cat > /tools/etc/vimrc << "EOF"
" Begin /tools/etc/vimrc

set nocompatible
set backspace=2
set ruler
syntax on

" End /tools/etc/vimrc
EOF
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

[ $PIPESTATUS = 0 ] && echo "$PROGRAM" > /tools/$0 || exit $PIPESTATUS

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
