#!/bin/bash -e

. $(dirname $0)/build-properties
. $(dirname $0)/pkgversion

PROGRAM="linux-${LINUX_VER}"
TARBALL="$PROGRAM.tar.xz"

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	xzcat ${SOURCE_DIR}/patch-${LINUX_VER}.21.xz | patch -Np1 -i -

	make mrproper
	make ARCH=x86_64 headers_check
	make ARCH=x86_64 INSTALL_HDR_PATH=/tools headers_install
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

[ $PIPESTATUS = 0 ] && echo "$PROGRAM" > /tools/$0 || exit $PIPESTATUS

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
