#!/bin/bash -e

. $(dirname $0)/build-properties
. $(dirname $0)/pkgversion

PROGRAM="binutils-${BINUTILS_VER}"
TARBALL="$PROGRAM.tar.xz"

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	mkdir -v build
	cd build
	
	AR=ar AS=as \
	../configure \
		--prefix=/cross-tools \
		--host=${CLFS_HOST} \
		--target=${CLFS_TARGET} \
		--with-sysroot=${CLFS} \
		--with-lib-path=/tools/lib:/tools/lib64 \
		--disable-nls \
		--disable-static \
		--enable-64-bit-bfd \
		--enable-gold=yes \
		--enable-plugins \
		--enable-threads \
		--disable-werror
	make
	make install
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

[ $PIPESTATUS = 0 ] && echo "$PROGRAM" > /tools/$0 || exit $PIPESTATUS

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
