#!/bin/bash -e

for script in $(ls | grep ^[0-9]); do
	if [ ! -f /tools/"$script" ]; then
		echo "$script"
		$(dirname $0)/$script
	fi
done

echo
echo "**************************************************"
echo "Toolchain build complete"
echo "Dont forget to run 'sudo chown -Rv 0:0 /mnt/clfs'"
echo "to change toolchain permission to root"
echo "**************************************************"
