#!/bin/bash

if [ "$(grep 'id:5:initdefault:' /etc/inittab)" ]; then
	echo " * Change default runlevel from 5 to 3"
	sed -i '/initdefault/ s/5/3/' /etc/inittab
else
	echo "Default runlevel already 3"
fi
