#!/bin/bash

if [ "$(grep 'id:3:initdefault:' /etc/inittab)" ]; then
	echo " * Change default runlevel from 3 to 5"
	sed -i '/initdefault/ s/3/5/' /etc/inittab
else
	echo "Default runlevel already 5"
fi
