#!/bin/bash

if [ ! $(getent group messagebus) ]; then
	groupadd -g 18 messagebus
	useradd -c "D-Bus Message Daemon User" -d /var/run/dbus \
			-u 18 -g messagebus -s /bin/false messagebus
else
	echo "group for messagebus exist."
fi
